services:
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=camicandy
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
  node:
    image: "node:16.17.0-alpine3.16"
    user: "node"
    working_dir: /home/node/backend_ingsoftware
    environment:
      - NODE_ENV=production
      - DEBUG=backend_ingsoftware:*
    volumes:
      - ./:/home/node/backend_ingsoftware
    expose:
      - "3000"
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    command: "npm start"
