services:
  postgresql:
    # used this variant image since `pgloader` is available on debian's repo
    image: postgres:16.3-bookworm
    container_name: postgresql
    environment:
      - POSTGRES_DB=camicandy
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
    volumes:
      - ./postgres:/var/lib/postgresql/data
  # phpmyadmin for postgres
  adminer:
    image: adminer
    ports:
      - 8081:8080
  mariadb:
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=camicandy
    volumes:
      - ./mysql:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:
      - PMA_HOST=mariadb
  node:
    image: "node:16.17.0-alpine3.16"
    container_name: backend_ingsoftware
    user: "node"
    working_dir: /home/node/backend_ingsoftware
    environment:
      - NODE_ENV=production
      - DEBUG=backend_ingsoftware:*
    volumes:
      - ./:/home/node/backend_ingsoftware
    expose:
      - "3000"
    ports: # use if it is necessary to expose the container to the host machine
      - "3000:3000"
    command: "npm start"
